package gampops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCollectParams creates a new CollectParams object
// with the default values initialized.
func NewCollectParams() *CollectParams {
	var (
		vDefault = string("1")
	)
	return &CollectParams{
		V: vDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCollectParamsWithTimeout creates a new CollectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCollectParamsWithTimeout(timeout time.Duration) *CollectParams {
	var (
		vDefault = string("1")
	)
	return &CollectParams{
		V: vDefault,

		timeout: timeout,
	}
}

// NewCollectParamsWithContext creates a new CollectParams object
// with the default values initialized, and the ability to set a context for a request
func NewCollectParamsWithContext(ctx context.Context) *CollectParams {
	var (
		vDefault = string("1")
	)
	return &CollectParams{
		V: vDefault,

		Context: ctx,
	}
}

// NewCollectParamsWithHTTPClient creates a new CollectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCollectParamsWithHTTPClient(client *http.Client) *CollectParams {
	var (
		vDefault = string("1")
	)
	return &CollectParams{
		V:          vDefault,
		HTTPClient: client,
	}
}

/*CollectParams contains all the parameters to send to the API endpoint
for the collect operation typically these are written to a http.Request
*/
type CollectParams struct {

	/*Aid
	  Application ID

	*/
	Aid *string
	/*Aiid
	  Application Installer ID

	*/
	Aiid *string
	/*Aip
	  Anonymize IP

	*/
	Aip *string
	/*An
	  Application Name

	*/
	An *string
	/*Av
	  Application Version

	*/
	Av *string
	/*Cc
	  Campaign Content

	*/
	Cc *string
	/*Cd
	  Screen Name

	*/
	Cd *string
	/*Ci
	  Campaign ID

	*/
	Ci *string
	/*Cid
	  Client ID

	*/
	Cid *string
	/*Ck
	  Campaign Keyword

	*/
	Ck *string
	/*Clt
	  Content Load Time

	*/
	Clt *int64
	/*Cm
	  Campaign Medium

	*/
	Cm *string
	/*Cn
	  Campaign Name

	*/
	Cn *string
	/*Col
	  Checkout Step Option

	*/
	Col *string
	/*Cos
	  Checkout Step

	*/
	Cos *int64
	/*Cs
	  Campaign Source

	*/
	Cs *string
	/*Cu
	  Currency Code

	*/
	Cu *string
	/*Dclid
	  Google Display Ads ID

	*/
	Dclid *string
	/*De
	  Document Encoding

	*/
	De *string
	/*Dh
	  Document Host Name

	*/
	Dh *string
	/*Dit
	  DOM Interactive Time

	*/
	Dit *int64
	/*Dl
	  Document location URL

	*/
	Dl *string
	/*DNS
	  DNS Time

	*/
	DNS *int64
	/*Dp
	  Document Path

	*/
	Dp *string
	/*Dr
	  Document Referrer

	*/
	Dr *string
	/*Ds
	  Data Source

	*/
	Ds *string
	/*Dt
	  Document Title

	*/
	Dt *string
	/*Ea
	  Event Action

	*/
	Ea *string
	/*Ec
	  Event Category

	*/
	Ec *string
	/*El
	  Event Label

	*/
	El *string
	/*Ev
	  Event Value

	*/
	Ev *int64
	/*Exd
	  Exception Description

	*/
	Exd *string
	/*Exf
	  Is Exception Fatal?

	*/
	Exf *bool
	/*Fl
	  Flash Version

	*/
	Fl *string
	/*Gclid
	  Google AdWords ID

	*/
	Gclid *string
	/*Geoid
	  Geographical Override

	*/
	Geoid *string
	/*Ic
	  Item Code

	*/
	Ic *string
	/*In
	  Item Name

	*/
	In *string
	/*IP
	  Item Price

	*/
	IP *float64
	/*Iq
	  Item Quantity

	*/
	Iq *int64
	/*Iv
	  Item Category

	*/
	Iv *string
	/*Je
	  Java Enabled

	*/
	Je *bool
	/*Linkid
	  Link ID

	*/
	Linkid *string
	/*Ni
	  Non-Interaction Hit

	*/
	Ni *bool
	/*Pa
	  Product Action

	*/
	Pa *string
	/*Pal
	  Product Action List

	*/
	Pal *string
	/*Pdt
	  Page Download Time

	*/
	Pdt *int64
	/*Plt
	  Page Load Time

	*/
	Plt *int64
	/*Promoa
	  Promotion Action

	*/
	Promoa *string
	/*Qt
	  Queue Time

	*/
	Qt *int64
	/*Rrt
	  Redirect Response Time

	*/
	Rrt *int64
	/*Sa
	  Social Action

	*/
	Sa *string
	/*Sc
	  Session Control

	*/
	Sc *string
	/*Sd
	  Screen Colors

	*/
	Sd *string
	/*Sn
	  Social Network

	*/
	Sn *string
	/*Sr
	  Screen Resolution

	*/
	Sr *string
	/*Srt
	  Server Response Time

	*/
	Srt *int64
	/*St
	  Social Action Target

	*/
	St *string
	/*T
	  Hit type

	*/
	T string
	/*Ta
	  Affiliation

	*/
	Ta *string
	/*Tcc
	  Coupon Code

	*/
	Tcc *string
	/*TCP
	  TCP Connect Time

	*/
	TCP *int64
	/*Ti
	  Transaction ID

	*/
	Ti *string
	/*Tid
	  Tracking ID / Web Property ID

	*/
	Tid string
	/*Tr
	  Revenue

	*/
	Tr *float64
	/*Ts
	  Shipping

	*/
	Ts *float64
	/*Tt
	  Tax

	*/
	Tt *float64
	/*Ua
	  User Agent Override

	*/
	Ua *string
	/*UID
	  User ID

	*/
	UID *string
	/*Uip
	  IP Override

	*/
	Uip *string
	/*Ul
	  User Language

	*/
	Ul *string
	/*Utc
	  User timing category

	*/
	Utc *string
	/*Utl
	  User timing label

	*/
	Utl *string
	/*Utt
	  User timing time

	*/
	Utt *int64
	/*Utv
	  User timing variable name

	*/
	Utv *string
	/*V
	  Protocol Version

	*/
	V string
	/*Vp
	  Viewport size

	*/
	Vp *string
	/*Xid
	  Experiment ID

	*/
	Xid *string
	/*Xvar
	  Experiment Variant

	*/
	Xvar *string
	/*Z
	  Cache Buster

	*/
	Z *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the collect params
func (o *CollectParams) WithTimeout(timeout time.Duration) *CollectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the collect params
func (o *CollectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the collect params
func (o *CollectParams) WithContext(ctx context.Context) *CollectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the collect params
func (o *CollectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the collect params
func (o *CollectParams) WithHTTPClient(client *http.Client) *CollectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the collect params
func (o *CollectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAid adds the aid to the collect params
func (o *CollectParams) WithAid(aid *string) *CollectParams {
	o.SetAid(aid)
	return o
}

// SetAid adds the aid to the collect params
func (o *CollectParams) SetAid(aid *string) {
	o.Aid = aid
}

// WithAiid adds the aiid to the collect params
func (o *CollectParams) WithAiid(aiid *string) *CollectParams {
	o.SetAiid(aiid)
	return o
}

// SetAiid adds the aiid to the collect params
func (o *CollectParams) SetAiid(aiid *string) {
	o.Aiid = aiid
}

// WithAip adds the aip to the collect params
func (o *CollectParams) WithAip(aip *string) *CollectParams {
	o.SetAip(aip)
	return o
}

// SetAip adds the aip to the collect params
func (o *CollectParams) SetAip(aip *string) {
	o.Aip = aip
}

// WithAn adds the an to the collect params
func (o *CollectParams) WithAn(an *string) *CollectParams {
	o.SetAn(an)
	return o
}

// SetAn adds the an to the collect params
func (o *CollectParams) SetAn(an *string) {
	o.An = an
}

// WithAv adds the av to the collect params
func (o *CollectParams) WithAv(av *string) *CollectParams {
	o.SetAv(av)
	return o
}

// SetAv adds the av to the collect params
func (o *CollectParams) SetAv(av *string) {
	o.Av = av
}

// WithCc adds the cc to the collect params
func (o *CollectParams) WithCc(cc *string) *CollectParams {
	o.SetCc(cc)
	return o
}

// SetCc adds the cc to the collect params
func (o *CollectParams) SetCc(cc *string) {
	o.Cc = cc
}

// WithCd adds the cd to the collect params
func (o *CollectParams) WithCd(cd *string) *CollectParams {
	o.SetCd(cd)
	return o
}

// SetCd adds the cd to the collect params
func (o *CollectParams) SetCd(cd *string) {
	o.Cd = cd
}

// WithCi adds the ci to the collect params
func (o *CollectParams) WithCi(ci *string) *CollectParams {
	o.SetCi(ci)
	return o
}

// SetCi adds the ci to the collect params
func (o *CollectParams) SetCi(ci *string) {
	o.Ci = ci
}

// WithCid adds the cid to the collect params
func (o *CollectParams) WithCid(cid *string) *CollectParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the collect params
func (o *CollectParams) SetCid(cid *string) {
	o.Cid = cid
}

// WithCk adds the ck to the collect params
func (o *CollectParams) WithCk(ck *string) *CollectParams {
	o.SetCk(ck)
	return o
}

// SetCk adds the ck to the collect params
func (o *CollectParams) SetCk(ck *string) {
	o.Ck = ck
}

// WithClt adds the clt to the collect params
func (o *CollectParams) WithClt(clt *int64) *CollectParams {
	o.SetClt(clt)
	return o
}

// SetClt adds the clt to the collect params
func (o *CollectParams) SetClt(clt *int64) {
	o.Clt = clt
}

// WithCm adds the cm to the collect params
func (o *CollectParams) WithCm(cm *string) *CollectParams {
	o.SetCm(cm)
	return o
}

// SetCm adds the cm to the collect params
func (o *CollectParams) SetCm(cm *string) {
	o.Cm = cm
}

// WithCn adds the cn to the collect params
func (o *CollectParams) WithCn(cn *string) *CollectParams {
	o.SetCn(cn)
	return o
}

// SetCn adds the cn to the collect params
func (o *CollectParams) SetCn(cn *string) {
	o.Cn = cn
}

// WithCol adds the col to the collect params
func (o *CollectParams) WithCol(col *string) *CollectParams {
	o.SetCol(col)
	return o
}

// SetCol adds the col to the collect params
func (o *CollectParams) SetCol(col *string) {
	o.Col = col
}

// WithCos adds the cos to the collect params
func (o *CollectParams) WithCos(cos *int64) *CollectParams {
	o.SetCos(cos)
	return o
}

// SetCos adds the cos to the collect params
func (o *CollectParams) SetCos(cos *int64) {
	o.Cos = cos
}

// WithCs adds the cs to the collect params
func (o *CollectParams) WithCs(cs *string) *CollectParams {
	o.SetCs(cs)
	return o
}

// SetCs adds the cs to the collect params
func (o *CollectParams) SetCs(cs *string) {
	o.Cs = cs
}

// WithCu adds the cu to the collect params
func (o *CollectParams) WithCu(cu *string) *CollectParams {
	o.SetCu(cu)
	return o
}

// SetCu adds the cu to the collect params
func (o *CollectParams) SetCu(cu *string) {
	o.Cu = cu
}

// WithDclid adds the dclid to the collect params
func (o *CollectParams) WithDclid(dclid *string) *CollectParams {
	o.SetDclid(dclid)
	return o
}

// SetDclid adds the dclid to the collect params
func (o *CollectParams) SetDclid(dclid *string) {
	o.Dclid = dclid
}

// WithDe adds the de to the collect params
func (o *CollectParams) WithDe(de *string) *CollectParams {
	o.SetDe(de)
	return o
}

// SetDe adds the de to the collect params
func (o *CollectParams) SetDe(de *string) {
	o.De = de
}

// WithDh adds the dh to the collect params
func (o *CollectParams) WithDh(dh *string) *CollectParams {
	o.SetDh(dh)
	return o
}

// SetDh adds the dh to the collect params
func (o *CollectParams) SetDh(dh *string) {
	o.Dh = dh
}

// WithDit adds the dit to the collect params
func (o *CollectParams) WithDit(dit *int64) *CollectParams {
	o.SetDit(dit)
	return o
}

// SetDit adds the dit to the collect params
func (o *CollectParams) SetDit(dit *int64) {
	o.Dit = dit
}

// WithDl adds the dl to the collect params
func (o *CollectParams) WithDl(dl *string) *CollectParams {
	o.SetDl(dl)
	return o
}

// SetDl adds the dl to the collect params
func (o *CollectParams) SetDl(dl *string) {
	o.Dl = dl
}

// WithDNS adds the dns to the collect params
func (o *CollectParams) WithDNS(dns *int64) *CollectParams {
	o.SetDNS(dns)
	return o
}

// SetDNS adds the dns to the collect params
func (o *CollectParams) SetDNS(dns *int64) {
	o.DNS = dns
}

// WithDp adds the dp to the collect params
func (o *CollectParams) WithDp(dp *string) *CollectParams {
	o.SetDp(dp)
	return o
}

// SetDp adds the dp to the collect params
func (o *CollectParams) SetDp(dp *string) {
	o.Dp = dp
}

// WithDr adds the dr to the collect params
func (o *CollectParams) WithDr(dr *string) *CollectParams {
	o.SetDr(dr)
	return o
}

// SetDr adds the dr to the collect params
func (o *CollectParams) SetDr(dr *string) {
	o.Dr = dr
}

// WithDs adds the ds to the collect params
func (o *CollectParams) WithDs(ds *string) *CollectParams {
	o.SetDs(ds)
	return o
}

// SetDs adds the ds to the collect params
func (o *CollectParams) SetDs(ds *string) {
	o.Ds = ds
}

// WithDt adds the dt to the collect params
func (o *CollectParams) WithDt(dt *string) *CollectParams {
	o.SetDt(dt)
	return o
}

// SetDt adds the dt to the collect params
func (o *CollectParams) SetDt(dt *string) {
	o.Dt = dt
}

// WithEa adds the ea to the collect params
func (o *CollectParams) WithEa(ea *string) *CollectParams {
	o.SetEa(ea)
	return o
}

// SetEa adds the ea to the collect params
func (o *CollectParams) SetEa(ea *string) {
	o.Ea = ea
}

// WithEc adds the ec to the collect params
func (o *CollectParams) WithEc(ec *string) *CollectParams {
	o.SetEc(ec)
	return o
}

// SetEc adds the ec to the collect params
func (o *CollectParams) SetEc(ec *string) {
	o.Ec = ec
}

// WithEl adds the el to the collect params
func (o *CollectParams) WithEl(el *string) *CollectParams {
	o.SetEl(el)
	return o
}

// SetEl adds the el to the collect params
func (o *CollectParams) SetEl(el *string) {
	o.El = el
}

// WithEv adds the ev to the collect params
func (o *CollectParams) WithEv(ev *int64) *CollectParams {
	o.SetEv(ev)
	return o
}

// SetEv adds the ev to the collect params
func (o *CollectParams) SetEv(ev *int64) {
	o.Ev = ev
}

// WithExd adds the exd to the collect params
func (o *CollectParams) WithExd(exd *string) *CollectParams {
	o.SetExd(exd)
	return o
}

// SetExd adds the exd to the collect params
func (o *CollectParams) SetExd(exd *string) {
	o.Exd = exd
}

// WithExf adds the exf to the collect params
func (o *CollectParams) WithExf(exf *bool) *CollectParams {
	o.SetExf(exf)
	return o
}

// SetExf adds the exf to the collect params
func (o *CollectParams) SetExf(exf *bool) {
	o.Exf = exf
}

// WithFl adds the fl to the collect params
func (o *CollectParams) WithFl(fl *string) *CollectParams {
	o.SetFl(fl)
	return o
}

// SetFl adds the fl to the collect params
func (o *CollectParams) SetFl(fl *string) {
	o.Fl = fl
}

// WithGclid adds the gclid to the collect params
func (o *CollectParams) WithGclid(gclid *string) *CollectParams {
	o.SetGclid(gclid)
	return o
}

// SetGclid adds the gclid to the collect params
func (o *CollectParams) SetGclid(gclid *string) {
	o.Gclid = gclid
}

// WithGeoid adds the geoid to the collect params
func (o *CollectParams) WithGeoid(geoid *string) *CollectParams {
	o.SetGeoid(geoid)
	return o
}

// SetGeoid adds the geoid to the collect params
func (o *CollectParams) SetGeoid(geoid *string) {
	o.Geoid = geoid
}

// WithIc adds the ic to the collect params
func (o *CollectParams) WithIc(ic *string) *CollectParams {
	o.SetIc(ic)
	return o
}

// SetIc adds the ic to the collect params
func (o *CollectParams) SetIc(ic *string) {
	o.Ic = ic
}

// WithIn adds the in to the collect params
func (o *CollectParams) WithIn(in *string) *CollectParams {
	o.SetIn(in)
	return o
}

// SetIn adds the in to the collect params
func (o *CollectParams) SetIn(in *string) {
	o.In = in
}

// WithIP adds the ip to the collect params
func (o *CollectParams) WithIP(ip *float64) *CollectParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the collect params
func (o *CollectParams) SetIP(ip *float64) {
	o.IP = ip
}

// WithIq adds the iq to the collect params
func (o *CollectParams) WithIq(iq *int64) *CollectParams {
	o.SetIq(iq)
	return o
}

// SetIq adds the iq to the collect params
func (o *CollectParams) SetIq(iq *int64) {
	o.Iq = iq
}

// WithIv adds the iv to the collect params
func (o *CollectParams) WithIv(iv *string) *CollectParams {
	o.SetIv(iv)
	return o
}

// SetIv adds the iv to the collect params
func (o *CollectParams) SetIv(iv *string) {
	o.Iv = iv
}

// WithJe adds the je to the collect params
func (o *CollectParams) WithJe(je *bool) *CollectParams {
	o.SetJe(je)
	return o
}

// SetJe adds the je to the collect params
func (o *CollectParams) SetJe(je *bool) {
	o.Je = je
}

// WithLinkid adds the linkid to the collect params
func (o *CollectParams) WithLinkid(linkid *string) *CollectParams {
	o.SetLinkid(linkid)
	return o
}

// SetLinkid adds the linkid to the collect params
func (o *CollectParams) SetLinkid(linkid *string) {
	o.Linkid = linkid
}

// WithNi adds the ni to the collect params
func (o *CollectParams) WithNi(ni *bool) *CollectParams {
	o.SetNi(ni)
	return o
}

// SetNi adds the ni to the collect params
func (o *CollectParams) SetNi(ni *bool) {
	o.Ni = ni
}

// WithPa adds the pa to the collect params
func (o *CollectParams) WithPa(pa *string) *CollectParams {
	o.SetPa(pa)
	return o
}

// SetPa adds the pa to the collect params
func (o *CollectParams) SetPa(pa *string) {
	o.Pa = pa
}

// WithPal adds the pal to the collect params
func (o *CollectParams) WithPal(pal *string) *CollectParams {
	o.SetPal(pal)
	return o
}

// SetPal adds the pal to the collect params
func (o *CollectParams) SetPal(pal *string) {
	o.Pal = pal
}

// WithPdt adds the pdt to the collect params
func (o *CollectParams) WithPdt(pdt *int64) *CollectParams {
	o.SetPdt(pdt)
	return o
}

// SetPdt adds the pdt to the collect params
func (o *CollectParams) SetPdt(pdt *int64) {
	o.Pdt = pdt
}

// WithPlt adds the plt to the collect params
func (o *CollectParams) WithPlt(plt *int64) *CollectParams {
	o.SetPlt(plt)
	return o
}

// SetPlt adds the plt to the collect params
func (o *CollectParams) SetPlt(plt *int64) {
	o.Plt = plt
}

// WithPromoa adds the promoa to the collect params
func (o *CollectParams) WithPromoa(promoa *string) *CollectParams {
	o.SetPromoa(promoa)
	return o
}

// SetPromoa adds the promoa to the collect params
func (o *CollectParams) SetPromoa(promoa *string) {
	o.Promoa = promoa
}

// WithQt adds the qt to the collect params
func (o *CollectParams) WithQt(qt *int64) *CollectParams {
	o.SetQt(qt)
	return o
}

// SetQt adds the qt to the collect params
func (o *CollectParams) SetQt(qt *int64) {
	o.Qt = qt
}

// WithRrt adds the rrt to the collect params
func (o *CollectParams) WithRrt(rrt *int64) *CollectParams {
	o.SetRrt(rrt)
	return o
}

// SetRrt adds the rrt to the collect params
func (o *CollectParams) SetRrt(rrt *int64) {
	o.Rrt = rrt
}

// WithSa adds the sa to the collect params
func (o *CollectParams) WithSa(sa *string) *CollectParams {
	o.SetSa(sa)
	return o
}

// SetSa adds the sa to the collect params
func (o *CollectParams) SetSa(sa *string) {
	o.Sa = sa
}

// WithSc adds the sc to the collect params
func (o *CollectParams) WithSc(sc *string) *CollectParams {
	o.SetSc(sc)
	return o
}

// SetSc adds the sc to the collect params
func (o *CollectParams) SetSc(sc *string) {
	o.Sc = sc
}

// WithSd adds the sd to the collect params
func (o *CollectParams) WithSd(sd *string) *CollectParams {
	o.SetSd(sd)
	return o
}

// SetSd adds the sd to the collect params
func (o *CollectParams) SetSd(sd *string) {
	o.Sd = sd
}

// WithSn adds the sn to the collect params
func (o *CollectParams) WithSn(sn *string) *CollectParams {
	o.SetSn(sn)
	return o
}

// SetSn adds the sn to the collect params
func (o *CollectParams) SetSn(sn *string) {
	o.Sn = sn
}

// WithSr adds the sr to the collect params
func (o *CollectParams) WithSr(sr *string) *CollectParams {
	o.SetSr(sr)
	return o
}

// SetSr adds the sr to the collect params
func (o *CollectParams) SetSr(sr *string) {
	o.Sr = sr
}

// WithSrt adds the srt to the collect params
func (o *CollectParams) WithSrt(srt *int64) *CollectParams {
	o.SetSrt(srt)
	return o
}

// SetSrt adds the srt to the collect params
func (o *CollectParams) SetSrt(srt *int64) {
	o.Srt = srt
}

// WithSt adds the st to the collect params
func (o *CollectParams) WithSt(st *string) *CollectParams {
	o.SetSt(st)
	return o
}

// SetSt adds the st to the collect params
func (o *CollectParams) SetSt(st *string) {
	o.St = st
}

// WithT adds the t to the collect params
func (o *CollectParams) WithT(t string) *CollectParams {
	o.SetT(t)
	return o
}

// SetT adds the t to the collect params
func (o *CollectParams) SetT(t string) {
	o.T = t
}

// WithTa adds the ta to the collect params
func (o *CollectParams) WithTa(ta *string) *CollectParams {
	o.SetTa(ta)
	return o
}

// SetTa adds the ta to the collect params
func (o *CollectParams) SetTa(ta *string) {
	o.Ta = ta
}

// WithTcc adds the tcc to the collect params
func (o *CollectParams) WithTcc(tcc *string) *CollectParams {
	o.SetTcc(tcc)
	return o
}

// SetTcc adds the tcc to the collect params
func (o *CollectParams) SetTcc(tcc *string) {
	o.Tcc = tcc
}

// WithTCP adds the tcp to the collect params
func (o *CollectParams) WithTCP(tcp *int64) *CollectParams {
	o.SetTCP(tcp)
	return o
}

// SetTCP adds the tcp to the collect params
func (o *CollectParams) SetTCP(tcp *int64) {
	o.TCP = tcp
}

// WithTi adds the ti to the collect params
func (o *CollectParams) WithTi(ti *string) *CollectParams {
	o.SetTi(ti)
	return o
}

// SetTi adds the ti to the collect params
func (o *CollectParams) SetTi(ti *string) {
	o.Ti = ti
}

// WithTid adds the tid to the collect params
func (o *CollectParams) WithTid(tid string) *CollectParams {
	o.SetTid(tid)
	return o
}

// SetTid adds the tid to the collect params
func (o *CollectParams) SetTid(tid string) {
	o.Tid = tid
}

// WithTr adds the tr to the collect params
func (o *CollectParams) WithTr(tr *float64) *CollectParams {
	o.SetTr(tr)
	return o
}

// SetTr adds the tr to the collect params
func (o *CollectParams) SetTr(tr *float64) {
	o.Tr = tr
}

// WithTs adds the ts to the collect params
func (o *CollectParams) WithTs(ts *float64) *CollectParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the collect params
func (o *CollectParams) SetTs(ts *float64) {
	o.Ts = ts
}

// WithTt adds the tt to the collect params
func (o *CollectParams) WithTt(tt *float64) *CollectParams {
	o.SetTt(tt)
	return o
}

// SetTt adds the tt to the collect params
func (o *CollectParams) SetTt(tt *float64) {
	o.Tt = tt
}

// WithUa adds the ua to the collect params
func (o *CollectParams) WithUa(ua *string) *CollectParams {
	o.SetUa(ua)
	return o
}

// SetUa adds the ua to the collect params
func (o *CollectParams) SetUa(ua *string) {
	o.Ua = ua
}

// WithUID adds the uid to the collect params
func (o *CollectParams) WithUID(uid *string) *CollectParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the collect params
func (o *CollectParams) SetUID(uid *string) {
	o.UID = uid
}

// WithUip adds the uip to the collect params
func (o *CollectParams) WithUip(uip *string) *CollectParams {
	o.SetUip(uip)
	return o
}

// SetUip adds the uip to the collect params
func (o *CollectParams) SetUip(uip *string) {
	o.Uip = uip
}

// WithUl adds the ul to the collect params
func (o *CollectParams) WithUl(ul *string) *CollectParams {
	o.SetUl(ul)
	return o
}

// SetUl adds the ul to the collect params
func (o *CollectParams) SetUl(ul *string) {
	o.Ul = ul
}

// WithUtc adds the utc to the collect params
func (o *CollectParams) WithUtc(utc *string) *CollectParams {
	o.SetUtc(utc)
	return o
}

// SetUtc adds the utc to the collect params
func (o *CollectParams) SetUtc(utc *string) {
	o.Utc = utc
}

// WithUtl adds the utl to the collect params
func (o *CollectParams) WithUtl(utl *string) *CollectParams {
	o.SetUtl(utl)
	return o
}

// SetUtl adds the utl to the collect params
func (o *CollectParams) SetUtl(utl *string) {
	o.Utl = utl
}

// WithUtt adds the utt to the collect params
func (o *CollectParams) WithUtt(utt *int64) *CollectParams {
	o.SetUtt(utt)
	return o
}

// SetUtt adds the utt to the collect params
func (o *CollectParams) SetUtt(utt *int64) {
	o.Utt = utt
}

// WithUtv adds the utv to the collect params
func (o *CollectParams) WithUtv(utv *string) *CollectParams {
	o.SetUtv(utv)
	return o
}

// SetUtv adds the utv to the collect params
func (o *CollectParams) SetUtv(utv *string) {
	o.Utv = utv
}

// WithV adds the v to the collect params
func (o *CollectParams) WithV(v string) *CollectParams {
	o.SetV(v)
	return o
}

// SetV adds the v to the collect params
func (o *CollectParams) SetV(v string) {
	o.V = v
}

// WithVp adds the vp to the collect params
func (o *CollectParams) WithVp(vp *string) *CollectParams {
	o.SetVp(vp)
	return o
}

// SetVp adds the vp to the collect params
func (o *CollectParams) SetVp(vp *string) {
	o.Vp = vp
}

// WithXid adds the xid to the collect params
func (o *CollectParams) WithXid(xid *string) *CollectParams {
	o.SetXid(xid)
	return o
}

// SetXid adds the xid to the collect params
func (o *CollectParams) SetXid(xid *string) {
	o.Xid = xid
}

// WithXvar adds the xvar to the collect params
func (o *CollectParams) WithXvar(xvar *string) *CollectParams {
	o.SetXvar(xvar)
	return o
}

// SetXvar adds the xvar to the collect params
func (o *CollectParams) SetXvar(xvar *string) {
	o.Xvar = xvar
}

// WithZ adds the z to the collect params
func (o *CollectParams) WithZ(z *string) *CollectParams {
	o.SetZ(z)
	return o
}

// SetZ adds the z to the collect params
func (o *CollectParams) SetZ(z *string) {
	o.Z = z
}

// WriteToRequest writes these params to a swagger request
func (o *CollectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Aid != nil {

		// form param aid
		var frAid string
		if o.Aid != nil {
			frAid = *o.Aid
		}
		fAid := frAid
		if fAid != "" {
			if err := r.SetFormParam("aid", fAid); err != nil {
				return err
			}
		}

	}

	if o.Aiid != nil {

		// form param aiid
		var frAiid string
		if o.Aiid != nil {
			frAiid = *o.Aiid
		}
		fAiid := frAiid
		if fAiid != "" {
			if err := r.SetFormParam("aiid", fAiid); err != nil {
				return err
			}
		}

	}

	if o.Aip != nil {

		// form param aip
		var frAip string
		if o.Aip != nil {
			frAip = *o.Aip
		}
		fAip := frAip
		if fAip != "" {
			if err := r.SetFormParam("aip", fAip); err != nil {
				return err
			}
		}

	}

	if o.An != nil {

		// form param an
		var frAn string
		if o.An != nil {
			frAn = *o.An
		}
		fAn := frAn
		if fAn != "" {
			if err := r.SetFormParam("an", fAn); err != nil {
				return err
			}
		}

	}

	if o.Av != nil {

		// form param av
		var frAv string
		if o.Av != nil {
			frAv = *o.Av
		}
		fAv := frAv
		if fAv != "" {
			if err := r.SetFormParam("av", fAv); err != nil {
				return err
			}
		}

	}

	if o.Cc != nil {

		// form param cc
		var frCc string
		if o.Cc != nil {
			frCc = *o.Cc
		}
		fCc := frCc
		if fCc != "" {
			if err := r.SetFormParam("cc", fCc); err != nil {
				return err
			}
		}

	}

	if o.Cd != nil {

		// form param cd
		var frCd string
		if o.Cd != nil {
			frCd = *o.Cd
		}
		fCd := frCd
		if fCd != "" {
			if err := r.SetFormParam("cd", fCd); err != nil {
				return err
			}
		}

	}

	if o.Ci != nil {

		// form param ci
		var frCi string
		if o.Ci != nil {
			frCi = *o.Ci
		}
		fCi := frCi
		if fCi != "" {
			if err := r.SetFormParam("ci", fCi); err != nil {
				return err
			}
		}

	}

	if o.Cid != nil {

		// form param cid
		var frCid string
		if o.Cid != nil {
			frCid = *o.Cid
		}
		fCid := frCid
		if fCid != "" {
			if err := r.SetFormParam("cid", fCid); err != nil {
				return err
			}
		}

	}

	if o.Ck != nil {

		// form param ck
		var frCk string
		if o.Ck != nil {
			frCk = *o.Ck
		}
		fCk := frCk
		if fCk != "" {
			if err := r.SetFormParam("ck", fCk); err != nil {
				return err
			}
		}

	}

	if o.Clt != nil {

		// form param clt
		var frClt int64
		if o.Clt != nil {
			frClt = *o.Clt
		}
		fClt := swag.FormatInt64(frClt)
		if fClt != "" {
			if err := r.SetFormParam("clt", fClt); err != nil {
				return err
			}
		}

	}

	if o.Cm != nil {

		// form param cm
		var frCm string
		if o.Cm != nil {
			frCm = *o.Cm
		}
		fCm := frCm
		if fCm != "" {
			if err := r.SetFormParam("cm", fCm); err != nil {
				return err
			}
		}

	}

	if o.Cn != nil {

		// form param cn
		var frCn string
		if o.Cn != nil {
			frCn = *o.Cn
		}
		fCn := frCn
		if fCn != "" {
			if err := r.SetFormParam("cn", fCn); err != nil {
				return err
			}
		}

	}

	if o.Col != nil {

		// form param col
		var frCol string
		if o.Col != nil {
			frCol = *o.Col
		}
		fCol := frCol
		if fCol != "" {
			if err := r.SetFormParam("col", fCol); err != nil {
				return err
			}
		}

	}

	if o.Cos != nil {

		// form param cos
		var frCos int64
		if o.Cos != nil {
			frCos = *o.Cos
		}
		fCos := swag.FormatInt64(frCos)
		if fCos != "" {
			if err := r.SetFormParam("cos", fCos); err != nil {
				return err
			}
		}

	}

	if o.Cs != nil {

		// form param cs
		var frCs string
		if o.Cs != nil {
			frCs = *o.Cs
		}
		fCs := frCs
		if fCs != "" {
			if err := r.SetFormParam("cs", fCs); err != nil {
				return err
			}
		}

	}

	if o.Cu != nil {

		// form param cu
		var frCu string
		if o.Cu != nil {
			frCu = *o.Cu
		}
		fCu := frCu
		if fCu != "" {
			if err := r.SetFormParam("cu", fCu); err != nil {
				return err
			}
		}

	}

	if o.Dclid != nil {

		// form param dclid
		var frDclid string
		if o.Dclid != nil {
			frDclid = *o.Dclid
		}
		fDclid := frDclid
		if fDclid != "" {
			if err := r.SetFormParam("dclid", fDclid); err != nil {
				return err
			}
		}

	}

	if o.De != nil {

		// form param de
		var frDe string
		if o.De != nil {
			frDe = *o.De
		}
		fDe := frDe
		if fDe != "" {
			if err := r.SetFormParam("de", fDe); err != nil {
				return err
			}
		}

	}

	if o.Dh != nil {

		// form param dh
		var frDh string
		if o.Dh != nil {
			frDh = *o.Dh
		}
		fDh := frDh
		if fDh != "" {
			if err := r.SetFormParam("dh", fDh); err != nil {
				return err
			}
		}

	}

	if o.Dit != nil {

		// form param dit
		var frDit int64
		if o.Dit != nil {
			frDit = *o.Dit
		}
		fDit := swag.FormatInt64(frDit)
		if fDit != "" {
			if err := r.SetFormParam("dit", fDit); err != nil {
				return err
			}
		}

	}

	if o.Dl != nil {

		// form param dl
		var frDl string
		if o.Dl != nil {
			frDl = *o.Dl
		}
		fDl := frDl
		if fDl != "" {
			if err := r.SetFormParam("dl", fDl); err != nil {
				return err
			}
		}

	}

	if o.DNS != nil {

		// form param dns
		var frDNS int64
		if o.DNS != nil {
			frDNS = *o.DNS
		}
		fDNS := swag.FormatInt64(frDNS)
		if fDNS != "" {
			if err := r.SetFormParam("dns", fDNS); err != nil {
				return err
			}
		}

	}

	if o.Dp != nil {

		// form param dp
		var frDp string
		if o.Dp != nil {
			frDp = *o.Dp
		}
		fDp := frDp
		if fDp != "" {
			if err := r.SetFormParam("dp", fDp); err != nil {
				return err
			}
		}

	}

	if o.Dr != nil {

		// form param dr
		var frDr string
		if o.Dr != nil {
			frDr = *o.Dr
		}
		fDr := frDr
		if fDr != "" {
			if err := r.SetFormParam("dr", fDr); err != nil {
				return err
			}
		}

	}

	if o.Ds != nil {

		// form param ds
		var frDs string
		if o.Ds != nil {
			frDs = *o.Ds
		}
		fDs := frDs
		if fDs != "" {
			if err := r.SetFormParam("ds", fDs); err != nil {
				return err
			}
		}

	}

	if o.Dt != nil {

		// form param dt
		var frDt string
		if o.Dt != nil {
			frDt = *o.Dt
		}
		fDt := frDt
		if fDt != "" {
			if err := r.SetFormParam("dt", fDt); err != nil {
				return err
			}
		}

	}

	if o.Ea != nil {

		// form param ea
		var frEa string
		if o.Ea != nil {
			frEa = *o.Ea
		}
		fEa := frEa
		if fEa != "" {
			if err := r.SetFormParam("ea", fEa); err != nil {
				return err
			}
		}

	}

	if o.Ec != nil {

		// form param ec
		var frEc string
		if o.Ec != nil {
			frEc = *o.Ec
		}
		fEc := frEc
		if fEc != "" {
			if err := r.SetFormParam("ec", fEc); err != nil {
				return err
			}
		}

	}

	if o.El != nil {

		// form param el
		var frEl string
		if o.El != nil {
			frEl = *o.El
		}
		fEl := frEl
		if fEl != "" {
			if err := r.SetFormParam("el", fEl); err != nil {
				return err
			}
		}

	}

	if o.Ev != nil {

		// form param ev
		var frEv int64
		if o.Ev != nil {
			frEv = *o.Ev
		}
		fEv := swag.FormatInt64(frEv)
		if fEv != "" {
			if err := r.SetFormParam("ev", fEv); err != nil {
				return err
			}
		}

	}

	if o.Exd != nil {

		// form param exd
		var frExd string
		if o.Exd != nil {
			frExd = *o.Exd
		}
		fExd := frExd
		if fExd != "" {
			if err := r.SetFormParam("exd", fExd); err != nil {
				return err
			}
		}

	}

	if o.Exf != nil {

		// form param exf
		var frExf bool
		if o.Exf != nil {
			frExf = *o.Exf
		}
		fExf := swag.FormatBool(frExf)
		if fExf != "" {
			if err := r.SetFormParam("exf", fExf); err != nil {
				return err
			}
		}

	}

	if o.Fl != nil {

		// form param fl
		var frFl string
		if o.Fl != nil {
			frFl = *o.Fl
		}
		fFl := frFl
		if fFl != "" {
			if err := r.SetFormParam("fl", fFl); err != nil {
				return err
			}
		}

	}

	if o.Gclid != nil {

		// form param gclid
		var frGclid string
		if o.Gclid != nil {
			frGclid = *o.Gclid
		}
		fGclid := frGclid
		if fGclid != "" {
			if err := r.SetFormParam("gclid", fGclid); err != nil {
				return err
			}
		}

	}

	if o.Geoid != nil {

		// form param geoid
		var frGeoid string
		if o.Geoid != nil {
			frGeoid = *o.Geoid
		}
		fGeoid := frGeoid
		if fGeoid != "" {
			if err := r.SetFormParam("geoid", fGeoid); err != nil {
				return err
			}
		}

	}

	if o.Ic != nil {

		// form param ic
		var frIc string
		if o.Ic != nil {
			frIc = *o.Ic
		}
		fIc := frIc
		if fIc != "" {
			if err := r.SetFormParam("ic", fIc); err != nil {
				return err
			}
		}

	}

	if o.In != nil {

		// form param in
		var frIn string
		if o.In != nil {
			frIn = *o.In
		}
		fIn := frIn
		if fIn != "" {
			if err := r.SetFormParam("in", fIn); err != nil {
				return err
			}
		}

	}

	if o.IP != nil {

		// form param ip
		var frIP float64
		if o.IP != nil {
			frIP = *o.IP
		}
		fIP := swag.FormatFloat64(frIP)
		if fIP != "" {
			if err := r.SetFormParam("ip", fIP); err != nil {
				return err
			}
		}

	}

	if o.Iq != nil {

		// form param iq
		var frIq int64
		if o.Iq != nil {
			frIq = *o.Iq
		}
		fIq := swag.FormatInt64(frIq)
		if fIq != "" {
			if err := r.SetFormParam("iq", fIq); err != nil {
				return err
			}
		}

	}

	if o.Iv != nil {

		// form param iv
		var frIv string
		if o.Iv != nil {
			frIv = *o.Iv
		}
		fIv := frIv
		if fIv != "" {
			if err := r.SetFormParam("iv", fIv); err != nil {
				return err
			}
		}

	}

	if o.Je != nil {

		// form param je
		var frJe bool
		if o.Je != nil {
			frJe = *o.Je
		}
		fJe := swag.FormatBool(frJe)
		if fJe != "" {
			if err := r.SetFormParam("je", fJe); err != nil {
				return err
			}
		}

	}

	if o.Linkid != nil {

		// form param linkid
		var frLinkid string
		if o.Linkid != nil {
			frLinkid = *o.Linkid
		}
		fLinkid := frLinkid
		if fLinkid != "" {
			if err := r.SetFormParam("linkid", fLinkid); err != nil {
				return err
			}
		}

	}

	if o.Ni != nil {

		// form param ni
		var frNi bool
		if o.Ni != nil {
			frNi = *o.Ni
		}
		fNi := swag.FormatBool(frNi)
		if fNi != "" {
			if err := r.SetFormParam("ni", fNi); err != nil {
				return err
			}
		}

	}

	if o.Pa != nil {

		// form param pa
		var frPa string
		if o.Pa != nil {
			frPa = *o.Pa
		}
		fPa := frPa
		if fPa != "" {
			if err := r.SetFormParam("pa", fPa); err != nil {
				return err
			}
		}

	}

	if o.Pal != nil {

		// form param pal
		var frPal string
		if o.Pal != nil {
			frPal = *o.Pal
		}
		fPal := frPal
		if fPal != "" {
			if err := r.SetFormParam("pal", fPal); err != nil {
				return err
			}
		}

	}

	if o.Pdt != nil {

		// form param pdt
		var frPdt int64
		if o.Pdt != nil {
			frPdt = *o.Pdt
		}
		fPdt := swag.FormatInt64(frPdt)
		if fPdt != "" {
			if err := r.SetFormParam("pdt", fPdt); err != nil {
				return err
			}
		}

	}

	if o.Plt != nil {

		// form param plt
		var frPlt int64
		if o.Plt != nil {
			frPlt = *o.Plt
		}
		fPlt := swag.FormatInt64(frPlt)
		if fPlt != "" {
			if err := r.SetFormParam("plt", fPlt); err != nil {
				return err
			}
		}

	}

	if o.Promoa != nil {

		// form param promoa
		var frPromoa string
		if o.Promoa != nil {
			frPromoa = *o.Promoa
		}
		fPromoa := frPromoa
		if fPromoa != "" {
			if err := r.SetFormParam("promoa", fPromoa); err != nil {
				return err
			}
		}

	}

	if o.Qt != nil {

		// form param qt
		var frQt int64
		if o.Qt != nil {
			frQt = *o.Qt
		}
		fQt := swag.FormatInt64(frQt)
		if fQt != "" {
			if err := r.SetFormParam("qt", fQt); err != nil {
				return err
			}
		}

	}

	if o.Rrt != nil {

		// form param rrt
		var frRrt int64
		if o.Rrt != nil {
			frRrt = *o.Rrt
		}
		fRrt := swag.FormatInt64(frRrt)
		if fRrt != "" {
			if err := r.SetFormParam("rrt", fRrt); err != nil {
				return err
			}
		}

	}

	if o.Sa != nil {

		// form param sa
		var frSa string
		if o.Sa != nil {
			frSa = *o.Sa
		}
		fSa := frSa
		if fSa != "" {
			if err := r.SetFormParam("sa", fSa); err != nil {
				return err
			}
		}

	}

	if o.Sc != nil {

		// form param sc
		var frSc string
		if o.Sc != nil {
			frSc = *o.Sc
		}
		fSc := frSc
		if fSc != "" {
			if err := r.SetFormParam("sc", fSc); err != nil {
				return err
			}
		}

	}

	if o.Sd != nil {

		// form param sd
		var frSd string
		if o.Sd != nil {
			frSd = *o.Sd
		}
		fSd := frSd
		if fSd != "" {
			if err := r.SetFormParam("sd", fSd); err != nil {
				return err
			}
		}

	}

	if o.Sn != nil {

		// form param sn
		var frSn string
		if o.Sn != nil {
			frSn = *o.Sn
		}
		fSn := frSn
		if fSn != "" {
			if err := r.SetFormParam("sn", fSn); err != nil {
				return err
			}
		}

	}

	if o.Sr != nil {

		// form param sr
		var frSr string
		if o.Sr != nil {
			frSr = *o.Sr
		}
		fSr := frSr
		if fSr != "" {
			if err := r.SetFormParam("sr", fSr); err != nil {
				return err
			}
		}

	}

	if o.Srt != nil {

		// form param srt
		var frSrt int64
		if o.Srt != nil {
			frSrt = *o.Srt
		}
		fSrt := swag.FormatInt64(frSrt)
		if fSrt != "" {
			if err := r.SetFormParam("srt", fSrt); err != nil {
				return err
			}
		}

	}

	if o.St != nil {

		// form param st
		var frSt string
		if o.St != nil {
			frSt = *o.St
		}
		fSt := frSt
		if fSt != "" {
			if err := r.SetFormParam("st", fSt); err != nil {
				return err
			}
		}

	}

	// form param t
	frT := o.T
	fT := frT
	if fT != "" {
		if err := r.SetFormParam("t", fT); err != nil {
			return err
		}
	}

	if o.Ta != nil {

		// form param ta
		var frTa string
		if o.Ta != nil {
			frTa = *o.Ta
		}
		fTa := frTa
		if fTa != "" {
			if err := r.SetFormParam("ta", fTa); err != nil {
				return err
			}
		}

	}

	if o.Tcc != nil {

		// form param tcc
		var frTcc string
		if o.Tcc != nil {
			frTcc = *o.Tcc
		}
		fTcc := frTcc
		if fTcc != "" {
			if err := r.SetFormParam("tcc", fTcc); err != nil {
				return err
			}
		}

	}

	if o.TCP != nil {

		// form param tcp
		var frTCP int64
		if o.TCP != nil {
			frTCP = *o.TCP
		}
		fTCP := swag.FormatInt64(frTCP)
		if fTCP != "" {
			if err := r.SetFormParam("tcp", fTCP); err != nil {
				return err
			}
		}

	}

	if o.Ti != nil {

		// form param ti
		var frTi string
		if o.Ti != nil {
			frTi = *o.Ti
		}
		fTi := frTi
		if fTi != "" {
			if err := r.SetFormParam("ti", fTi); err != nil {
				return err
			}
		}

	}

	// form param tid
	frTid := o.Tid
	fTid := frTid
	if fTid != "" {
		if err := r.SetFormParam("tid", fTid); err != nil {
			return err
		}
	}

	if o.Tr != nil {

		// form param tr
		var frTr float64
		if o.Tr != nil {
			frTr = *o.Tr
		}
		fTr := swag.FormatFloat64(frTr)
		if fTr != "" {
			if err := r.SetFormParam("tr", fTr); err != nil {
				return err
			}
		}

	}

	if o.Ts != nil {

		// form param ts
		var frTs float64
		if o.Ts != nil {
			frTs = *o.Ts
		}
		fTs := swag.FormatFloat64(frTs)
		if fTs != "" {
			if err := r.SetFormParam("ts", fTs); err != nil {
				return err
			}
		}

	}

	if o.Tt != nil {

		// form param tt
		var frTt float64
		if o.Tt != nil {
			frTt = *o.Tt
		}
		fTt := swag.FormatFloat64(frTt)
		if fTt != "" {
			if err := r.SetFormParam("tt", fTt); err != nil {
				return err
			}
		}

	}

	if o.Ua != nil {

		// form param ua
		var frUa string
		if o.Ua != nil {
			frUa = *o.Ua
		}
		fUa := frUa
		if fUa != "" {
			if err := r.SetFormParam("ua", fUa); err != nil {
				return err
			}
		}

	}

	if o.UID != nil {

		// form param uid
		var frUID string
		if o.UID != nil {
			frUID = *o.UID
		}
		fUID := frUID
		if fUID != "" {
			if err := r.SetFormParam("uid", fUID); err != nil {
				return err
			}
		}

	}

	if o.Uip != nil {

		// form param uip
		var frUip string
		if o.Uip != nil {
			frUip = *o.Uip
		}
		fUip := frUip
		if fUip != "" {
			if err := r.SetFormParam("uip", fUip); err != nil {
				return err
			}
		}

	}

	if o.Ul != nil {

		// form param ul
		var frUl string
		if o.Ul != nil {
			frUl = *o.Ul
		}
		fUl := frUl
		if fUl != "" {
			if err := r.SetFormParam("ul", fUl); err != nil {
				return err
			}
		}

	}

	if o.Utc != nil {

		// form param utc
		var frUtc string
		if o.Utc != nil {
			frUtc = *o.Utc
		}
		fUtc := frUtc
		if fUtc != "" {
			if err := r.SetFormParam("utc", fUtc); err != nil {
				return err
			}
		}

	}

	if o.Utl != nil {

		// form param utl
		var frUtl string
		if o.Utl != nil {
			frUtl = *o.Utl
		}
		fUtl := frUtl
		if fUtl != "" {
			if err := r.SetFormParam("utl", fUtl); err != nil {
				return err
			}
		}

	}

	if o.Utt != nil {

		// form param utt
		var frUtt int64
		if o.Utt != nil {
			frUtt = *o.Utt
		}
		fUtt := swag.FormatInt64(frUtt)
		if fUtt != "" {
			if err := r.SetFormParam("utt", fUtt); err != nil {
				return err
			}
		}

	}

	if o.Utv != nil {

		// form param utv
		var frUtv string
		if o.Utv != nil {
			frUtv = *o.Utv
		}
		fUtv := frUtv
		if fUtv != "" {
			if err := r.SetFormParam("utv", fUtv); err != nil {
				return err
			}
		}

	}

	// form param v
	frV := o.V
	fV := frV
	if fV != "" {
		if err := r.SetFormParam("v", fV); err != nil {
			return err
		}
	}

	if o.Vp != nil {

		// form param vp
		var frVp string
		if o.Vp != nil {
			frVp = *o.Vp
		}
		fVp := frVp
		if fVp != "" {
			if err := r.SetFormParam("vp", fVp); err != nil {
				return err
			}
		}

	}

	if o.Xid != nil {

		// form param xid
		var frXid string
		if o.Xid != nil {
			frXid = *o.Xid
		}
		fXid := frXid
		if fXid != "" {
			if err := r.SetFormParam("xid", fXid); err != nil {
				return err
			}
		}

	}

	if o.Xvar != nil {

		// form param xvar
		var frXvar string
		if o.Xvar != nil {
			frXvar = *o.Xvar
		}
		fXvar := frXvar
		if fXvar != "" {
			if err := r.SetFormParam("xvar", fXvar); err != nil {
				return err
			}
		}

	}

	if o.Z != nil {

		// form param z
		var frZ string
		if o.Z != nil {
			frZ = *o.Z
		}
		fZ := frZ
		if fZ != "" {
			if err := r.SetFormParam("z", fZ); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
