package gampops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new gampops API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for gampops API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
Collect Send Measurements
*/
func (a *Client) Collect(params *CollectParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCollectParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Collect",
		Method:             "POST",
		PathPattern:        "/collect",
		ProducesMediaTypes: []string{"image/gif"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CollectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

/*
DebugCollect Debug Measurements
*/
func (a *Client) DebugCollect(params *DebugCollectParams) (*DebugCollectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDebugCollectParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DebugCollect",
		Method:             "POST",
		PathPattern:        "/debug/collect",
		ProducesMediaTypes: []string{"image/gif"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DebugCollectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DebugCollectOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
